/**
 * Canonical audit-log action names. Kept as string constants (not a Prisma
 * enum) so new event types can be added without a schema migration — the
 * AuditLog.action column stays a plain string for flexibility.
 */
export const AuditAction = {
  // Authentication
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  AUTH_LOGIN_FAILED: "AUTH_LOGIN_FAILED",
  AUTH_LOGOUT: "AUTH_LOGOUT",
  AUTH_PASSWORD_CHANGED: "AUTH_PASSWORD_CHANGED",

  // System / observability
  SYSTEM_HEALTH_CHECK: "SYSTEM_HEALTH_CHECK",
  SYSTEM_DEEP_HEALTH_CHECK: "SYSTEM_DEEP_HEALTH_CHECK",

  // Auditing itself
  AUDIT_LOG_VIEWED: "AUDIT_LOG_VIEWED",
  ACCESS_DENIED: "ACCESS_DENIED",

  // Clinic administration (settings page)
  CLINIC_UPDATED: "CLINIC_UPDATED",
  CLINIC_SETTINGS_UPDATED: "CLINIC_SETTINGS_UPDATED",

  // User management
  USER_UPDATED: "USER_UPDATED",
  USER_ROLE_CHANGED: "USER_ROLE_CHANGED",
  USER_STATUS_CHANGED: "USER_STATUS_CHANGED",
  USER_TEMP_PASSWORD_RESET: "USER_TEMP_PASSWORD_RESET",
  USER_ACCESS_DENIED: "USER_ACCESS_DENIED",

  // Patients
  PATIENT_CREATED: "PATIENT_CREATED",
  PATIENT_UPDATED: "PATIENT_UPDATED",
  PATIENT_STATUS_CHANGED: "PATIENT_STATUS_CHANGED",
  PATIENT_ARCHIVED: "PATIENT_ARCHIVED",
  PATIENT_ACCESS_DENIED: "PATIENT_ACCESS_DENIED",

  // Professionals
  PROFESSIONAL_CREATED: "PROFESSIONAL_CREATED",
  PROFESSIONAL_UPDATED: "PROFESSIONAL_UPDATED",
  PROFESSIONAL_STATUS_CHANGED: "PROFESSIONAL_STATUS_CHANGED",
  PROFESSIONAL_ACCESS_DENIED: "PROFESSIONAL_ACCESS_DENIED",

  // Working hours
  WORKING_HOUR_CREATED: "WORKING_HOUR_CREATED",
  WORKING_HOUR_UPDATED: "WORKING_HOUR_UPDATED",
  WORKING_HOUR_DELETED: "WORKING_HOUR_DELETED",
  WORKING_HOUR_STATUS_CHANGED: "WORKING_HOUR_STATUS_CHANGED",

  // Services
  SERVICE_CREATED: "SERVICE_CREATED",
  SERVICE_UPDATED: "SERVICE_UPDATED",
  SERVICE_STATUS_CHANGED: "SERVICE_STATUS_CHANGED",
  SERVICE_ACCESS_DENIED: "SERVICE_ACCESS_DENIED",

  // Professional <-> Service links
  PROFESSIONAL_SERVICE_LINKED: "PROFESSIONAL_SERVICE_LINKED",
  PROFESSIONAL_SERVICE_UNLINKED: "PROFESSIONAL_SERVICE_UNLINKED",

  // Appointments (agenda)
  APPOINTMENT_CREATED: "APPOINTMENT_CREATED",
  APPOINTMENT_UPDATED: "APPOINTMENT_UPDATED",
  APPOINTMENT_RESCHEDULED: "APPOINTMENT_RESCHEDULED",
  APPOINTMENT_CONFIRMED: "APPOINTMENT_CONFIRMED",
  APPOINTMENT_CANCELLED: "APPOINTMENT_CANCELLED",
  APPOINTMENT_COMPLETED: "APPOINTMENT_COMPLETED",
  APPOINTMENT_NO_SHOW: "APPOINTMENT_NO_SHOW",
  APPOINTMENT_ACCESS_DENIED: "APPOINTMENT_ACCESS_DENIED",

  // Conversations (central de atendimento)
  CONVERSATION_CREATED: "CONVERSATION_CREATED",
  CONVERSATION_UPDATED: "CONVERSATION_UPDATED",
  CONVERSATION_TAKEN: "CONVERSATION_TAKEN",
  CONVERSATION_ASSIGNED: "CONVERSATION_ASSIGNED",
  CONVERSATION_TRANSFERRED_TO_HUMAN: "CONVERSATION_TRANSFERRED_TO_HUMAN",
  CONVERSATION_RETURNED_TO_AI: "CONVERSATION_RETURNED_TO_AI",
  CONVERSATION_CLOSED: "CONVERSATION_CLOSED",
  CONVERSATION_REOPENED: "CONVERSATION_REOPENED",
  CONVERSATION_ACCESS_DENIED: "CONVERSATION_ACCESS_DENIED",
  MESSAGE_SENT: "MESSAGE_SENT",
  MESSAGE_RECEIVED_SIMULATED: "MESSAGE_RECEIVED_SIMULATED",

  // Sinery Assist (simulador) + configuração da IA
  ASSIST_SIMULATION_CREATED: "ASSIST_SIMULATION_CREATED",
  ASSIST_MESSAGE_RECEIVED: "ASSIST_MESSAGE_RECEIVED",
  ASSIST_MESSAGE_SENT: "ASSIST_MESSAGE_SENT",
  ASSIST_INTENT_DETECTED: "ASSIST_INTENT_DETECTED",
  ASSIST_TRANSFERRED_TO_HUMAN: "ASSIST_TRANSFERRED_TO_HUMAN",
  ASSIST_APPOINTMENT_CREATED: "ASSIST_APPOINTMENT_CREATED",
  ASSIST_APPOINTMENT_CONFIRMED: "ASSIST_APPOINTMENT_CONFIRMED",
  ASSIST_APPOINTMENT_CANCELLED: "ASSIST_APPOINTMENT_CANCELLED",
  ASSIST_APPOINTMENT_RESCHEDULED: "ASSIST_APPOINTMENT_RESCHEDULED",
  ASSIST_ACCESS_DENIED: "ASSIST_ACCESS_DENIED",
  AI_SETTINGS_UPDATED: "AI_SETTINGS_UPDATED",
  AI_KNOWLEDGE_CREATED: "AI_KNOWLEDGE_CREATED",
  AI_KNOWLEDGE_UPDATED: "AI_KNOWLEDGE_UPDATED",
  AI_KNOWLEDGE_STATUS_CHANGED: "AI_KNOWLEDGE_STATUS_CHANGED",

  // Sinery Assist — IA real (OpenAI)
  ASSIST_REAL_AI_USED: "ASSIST_REAL_AI_USED",
  ASSIST_RULE_BASED_FALLBACK_USED: "ASSIST_RULE_BASED_FALLBACK_USED",
  ASSIST_TOOL_REQUESTED: "ASSIST_TOOL_REQUESTED",
  ASSIST_TOOL_EXECUTED: "ASSIST_TOOL_EXECUTED",
  ASSIST_TOOL_FAILED: "ASSIST_TOOL_FAILED",
  ASSIST_INVALID_AI_OUTPUT: "ASSIST_INVALID_AI_OUTPUT",
  ASSIST_AI_PROVIDER_FAILED: "ASSIST_AI_PROVIDER_FAILED",
  ASSIST_SENSITIVE_MESSAGE_DETECTED: "ASSIST_SENSITIVE_MESSAGE_DETECTED",

  // Sinery Assist — flow lifecycle (Prompt 14)
  ASSIST_SCHEDULE_FLOW_STARTED: "ASSIST_SCHEDULE_FLOW_STARTED",
  ASSIST_RESCHEDULE_FLOW_STARTED: "ASSIST_RESCHEDULE_FLOW_STARTED",
  ASSIST_CANCEL_FLOW_STARTED: "ASSIST_CANCEL_FLOW_STARTED",
  ASSIST_CONFIRM_FLOW_STARTED: "ASSIST_CONFIRM_FLOW_STARTED",
  ASSIST_SLOTS_SUGGESTED: "ASSIST_SLOTS_SUGGESTED",
  ASSIST_SLOT_SELECTED: "ASSIST_SLOT_SELECTED",
  ASSIST_APPOINTMENT_SELECTED_FOR_RESCHEDULE: "ASSIST_APPOINTMENT_SELECTED_FOR_RESCHEDULE",
  ASSIST_APPOINTMENT_SELECTED_FOR_CANCEL: "ASSIST_APPOINTMENT_SELECTED_FOR_CANCEL",
  ASSIST_FLOW_CANCELLED_BY_PATIENT: "ASSIST_FLOW_CANCELLED_BY_PATIENT",
  ASSIST_FLOW_COMPLETED: "ASSIST_FLOW_COMPLETED",
  ASSIST_FLOW_FAILED: "ASSIST_FLOW_FAILED",

  // Sinery Assist — safety, cost & usage (Prompt 15)
  ASSIST_RATE_LIMIT_EXCEEDED: "ASSIST_RATE_LIMIT_EXCEEDED",
  ASSIST_DAILY_LIMIT_EXCEEDED: "ASSIST_DAILY_LIMIT_EXCEEDED",
  ASSIST_GLOBAL_DISABLED: "ASSIST_GLOBAL_DISABLED",
  ASSIST_CLINIC_DISABLED: "ASSIST_CLINIC_DISABLED",
  ASSIST_LOOP_DETECTED: "ASSIST_LOOP_DETECTED",
  ASSIST_HIGH_RISK_MESSAGE_DETECTED: "ASSIST_HIGH_RISK_MESSAGE_DETECTED",
  ASSIST_CRITICAL_RISK_MESSAGE_DETECTED: "ASSIST_CRITICAL_RISK_MESSAGE_DETECTED",
  ASSIST_PROMPT_INJECTION_DETECTED: "ASSIST_PROMPT_INJECTION_DETECTED",
  ASSIST_TOOL_BLOCKED: "ASSIST_TOOL_BLOCKED",
  ASSIST_USAGE_VIEWED: "ASSIST_USAGE_VIEWED",
  ASSIST_HEALTH_CHECKED: "ASSIST_HEALTH_CHECKED",

  // WhatsApp Cloud API integration (Prompt 16)
  WHATSAPP_INTEGRATION_VIEWED: "WHATSAPP_INTEGRATION_VIEWED",
  WHATSAPP_INTEGRATION_UPDATED: "WHATSAPP_INTEGRATION_UPDATED",
  WHATSAPP_CONFIG_CHECKED: "WHATSAPP_CONFIG_CHECKED",
  WHATSAPP_CONFIG_INVALID: "WHATSAPP_CONFIG_INVALID",
  WHATSAPP_CONFIG_READY: "WHATSAPP_CONFIG_READY",
  WHATSAPP_ACCESS_DENIED: "WHATSAPP_ACCESS_DENIED",

  // WhatsApp webhook (Prompt 17)
  WHATSAPP_WEBHOOK_VERIFIED: "WHATSAPP_WEBHOOK_VERIFIED",
  WHATSAPP_WEBHOOK_VERIFICATION_FAILED: "WHATSAPP_WEBHOOK_VERIFICATION_FAILED",
  WHATSAPP_WEBHOOK_RECEIVED: "WHATSAPP_WEBHOOK_RECEIVED",
  WHATSAPP_WEBHOOK_SIGNATURE_INVALID: "WHATSAPP_WEBHOOK_SIGNATURE_INVALID",
  WHATSAPP_WEBHOOK_DISABLED: "WHATSAPP_WEBHOOK_DISABLED",
  WHATSAPP_WEBHOOK_EVENT_IGNORED: "WHATSAPP_WEBHOOK_EVENT_IGNORED",
  WHATSAPP_MESSAGE_RECEIVED: "WHATSAPP_MESSAGE_RECEIVED",
  WHATSAPP_MESSAGE_DUPLICATE_IGNORED: "WHATSAPP_MESSAGE_DUPLICATE_IGNORED",
  WHATSAPP_STATUS_RECEIVED: "WHATSAPP_STATUS_RECEIVED",
  WHATSAPP_STATUS_FAILED_RECEIVED: "WHATSAPP_STATUS_FAILED_RECEIVED",
  CONVERSATION_CREATED_FROM_WHATSAPP: "CONVERSATION_CREATED_FROM_WHATSAPP",
  CONVERSATION_REOPENED_FROM_WHATSAPP: "CONVERSATION_REOPENED_FROM_WHATSAPP",
  PATIENT_MATCHED_FROM_WHATSAPP: "PATIENT_MATCHED_FROM_WHATSAPP",
  PATIENT_MATCH_AMBIGUOUS_FROM_WHATSAPP: "PATIENT_MATCH_AMBIGUOUS_FROM_WHATSAPP",
  PATIENT_CREATED_FROM_WHATSAPP: "PATIENT_CREATED_FROM_WHATSAPP",

  // Other domain events (used in seed samples)
  CLINIC_CREATED: "CLINIC_CREATED",
  USER_CREATED: "USER_CREATED",
} as const

export type AuditActionValue = (typeof AuditAction)[keyof typeof AuditAction]

/** Human-readable pt-BR labels for known actions, used by the audit UI. */
export const auditActionLabels: Record<string, string> = {
  AUTH_LOGIN_SUCCESS: "Login realizado",
  AUTH_LOGIN_FAILED: "Falha no login",
  AUTH_LOGOUT: "Logout",
  AUTH_PASSWORD_CHANGED: "Senha alterada",
  SYSTEM_HEALTH_CHECK: "Verificação de saúde",
  SYSTEM_DEEP_HEALTH_CHECK: "Verificação profunda",
  AUDIT_LOG_VIEWED: "Auditoria consultada",
  ACCESS_DENIED: "Acesso negado",
  CLINIC_UPDATED: "Clínica atualizada",
  CLINIC_SETTINGS_UPDATED: "Operação atualizada",
  USER_UPDATED: "Usuário atualizado",
  USER_ROLE_CHANGED: "Função alterada",
  USER_STATUS_CHANGED: "Status alterado",
  USER_TEMP_PASSWORD_RESET: "Senha provisória redefinida",
  USER_ACCESS_DENIED: "Acesso negado",
  PATIENT_CREATED: "Paciente criado",
  PATIENT_UPDATED: "Paciente atualizado",
  PATIENT_STATUS_CHANGED: "Status do paciente alterado",
  PATIENT_ARCHIVED: "Paciente arquivado",
  PATIENT_ACCESS_DENIED: "Acesso negado",
  PROFESSIONAL_CREATED: "Profissional criado",
  PROFESSIONAL_UPDATED: "Profissional atualizado",
  PROFESSIONAL_STATUS_CHANGED: "Status do profissional alterado",
  PROFESSIONAL_ACCESS_DENIED: "Acesso negado",
  WORKING_HOUR_CREATED: "Horário criado",
  WORKING_HOUR_UPDATED: "Horário atualizado",
  WORKING_HOUR_DELETED: "Horário removido",
  WORKING_HOUR_STATUS_CHANGED: "Status do horário alterado",
  SERVICE_CREATED: "Serviço criado",
  SERVICE_UPDATED: "Serviço atualizado",
  SERVICE_STATUS_CHANGED: "Status do serviço alterado",
  SERVICE_ACCESS_DENIED: "Acesso negado",
  PROFESSIONAL_SERVICE_LINKED: "Serviço vinculado ao profissional",
  PROFESSIONAL_SERVICE_UNLINKED: "Serviço desvinculado do profissional",
  APPOINTMENT_CREATED: "Consulta criada",
  APPOINTMENT_UPDATED: "Consulta atualizada",
  APPOINTMENT_RESCHEDULED: "Consulta remarcada",
  APPOINTMENT_CONFIRMED: "Consulta confirmada",
  APPOINTMENT_CANCELLED: "Consulta cancelada",
  APPOINTMENT_COMPLETED: "Consulta concluída",
  APPOINTMENT_NO_SHOW: "Falta registrada",
  APPOINTMENT_ACCESS_DENIED: "Acesso negado",
  CONVERSATION_CREATED: "Conversa criada",
  CONVERSATION_UPDATED: "Conversa atualizada",
  CONVERSATION_TAKEN: "Atendimento assumido",
  CONVERSATION_ASSIGNED: "Conversa atribuída",
  CONVERSATION_TRANSFERRED_TO_HUMAN: "Transferida para humano",
  CONVERSATION_RETURNED_TO_AI: "Devolvida para Sinery Assist",
  CONVERSATION_CLOSED: "Conversa encerrada",
  CONVERSATION_REOPENED: "Conversa reaberta",
  CONVERSATION_ACCESS_DENIED: "Acesso negado",
  MESSAGE_SENT: "Mensagem enviada",
  MESSAGE_RECEIVED_SIMULATED: "Mensagem recebida (simulada)",
  ASSIST_SIMULATION_CREATED: "Simulação criada",
  ASSIST_MESSAGE_RECEIVED: "Mensagem recebida pela Assist",
  ASSIST_MESSAGE_SENT: "Resposta da Assist",
  ASSIST_INTENT_DETECTED: "Intenção detectada",
  ASSIST_TRANSFERRED_TO_HUMAN: "Assist transferiu para humano",
  ASSIST_APPOINTMENT_CREATED: "Consulta criada pela Assist",
  ASSIST_APPOINTMENT_CONFIRMED: "Consulta confirmada pela Assist",
  ASSIST_APPOINTMENT_CANCELLED: "Consulta cancelada pela Assist",
  ASSIST_APPOINTMENT_RESCHEDULED: "Consulta remarcada pela Assist",
  ASSIST_ACCESS_DENIED: "Acesso negado",
  AI_SETTINGS_UPDATED: "Configuração da Assist atualizada",
  AI_KNOWLEDGE_CREATED: "Item de conhecimento criado",
  AI_KNOWLEDGE_UPDATED: "Item de conhecimento atualizado",
  AI_KNOWLEDGE_STATUS_CHANGED: "Status do conhecimento alterado",
  ASSIST_REAL_AI_USED: "IA real utilizada",
  ASSIST_RULE_BASED_FALLBACK_USED: "Fallback por regras utilizado",
  ASSIST_TOOL_REQUESTED: "Ferramenta solicitada pela IA",
  ASSIST_TOOL_EXECUTED: "Ferramenta executada",
  ASSIST_TOOL_FAILED: "Falha na ferramenta",
  ASSIST_INVALID_AI_OUTPUT: "Saída inválida da IA",
  ASSIST_AI_PROVIDER_FAILED: "Falha no provedor de IA",
  ASSIST_SENSITIVE_MESSAGE_DETECTED: "Mensagem sensível detectada",
  ASSIST_SCHEDULE_FLOW_STARTED: "Fluxo de agendamento iniciado",
  ASSIST_RESCHEDULE_FLOW_STARTED: "Fluxo de remarcação iniciado",
  ASSIST_CANCEL_FLOW_STARTED: "Fluxo de cancelamento iniciado",
  ASSIST_CONFIRM_FLOW_STARTED: "Fluxo de confirmação iniciado",
  ASSIST_SLOTS_SUGGESTED: "Horários sugeridos",
  ASSIST_SLOT_SELECTED: "Horário selecionado",
  ASSIST_APPOINTMENT_SELECTED_FOR_RESCHEDULE: "Consulta selecionada para remarcar",
  ASSIST_APPOINTMENT_SELECTED_FOR_CANCEL: "Consulta selecionada para cancelar",
  ASSIST_FLOW_CANCELLED_BY_PATIENT: "Fluxo cancelado pelo paciente",
  ASSIST_FLOW_COMPLETED: "Fluxo concluído",
  ASSIST_FLOW_FAILED: "Fluxo com falha",
  ASSIST_RATE_LIMIT_EXCEEDED: "Limite de requisições excedido",
  ASSIST_DAILY_LIMIT_EXCEEDED: "Limite diário excedido",
  ASSIST_GLOBAL_DISABLED: "Assist desativada globalmente",
  ASSIST_CLINIC_DISABLED: "Assist desativada na clínica",
  ASSIST_LOOP_DETECTED: "Loop de conversa detectado",
  ASSIST_HIGH_RISK_MESSAGE_DETECTED: "Mensagem de risco alto detectada",
  ASSIST_CRITICAL_RISK_MESSAGE_DETECTED: "Mensagem de risco crítico detectada",
  ASSIST_PROMPT_INJECTION_DETECTED: "Tentativa de prompt injection detectada",
  ASSIST_TOOL_BLOCKED: "Ferramenta bloqueada",
  ASSIST_USAGE_VIEWED: "Painel de uso da IA acessado",
  ASSIST_HEALTH_CHECKED: "Health check da IA executado",
  WHATSAPP_INTEGRATION_VIEWED: "Integração WhatsApp visualizada",
  WHATSAPP_INTEGRATION_UPDATED: "Integração WhatsApp atualizada",
  WHATSAPP_CONFIG_CHECKED: "Configuração WhatsApp verificada",
  WHATSAPP_CONFIG_INVALID: "Configuração WhatsApp inválida",
  WHATSAPP_CONFIG_READY: "Configuração WhatsApp pronta",
  WHATSAPP_ACCESS_DENIED: "Acesso negado à integração WhatsApp",
  WHATSAPP_WEBHOOK_VERIFIED: "Webhook WhatsApp verificado",
  WHATSAPP_WEBHOOK_VERIFICATION_FAILED: "Falha na verificação do webhook WhatsApp",
  WHATSAPP_WEBHOOK_RECEIVED: "Webhook WhatsApp recebido",
  WHATSAPP_WEBHOOK_SIGNATURE_INVALID: "Assinatura do webhook WhatsApp inválida",
  WHATSAPP_WEBHOOK_DISABLED: "Webhook WhatsApp desativado",
  WHATSAPP_WEBHOOK_EVENT_IGNORED: "Evento de webhook WhatsApp ignorado",
  WHATSAPP_MESSAGE_RECEIVED: "Mensagem recebida via WhatsApp",
  WHATSAPP_MESSAGE_DUPLICATE_IGNORED: "Mensagem WhatsApp duplicada ignorada",
  WHATSAPP_STATUS_RECEIVED: "Status WhatsApp recebido",
  WHATSAPP_STATUS_FAILED_RECEIVED: "Status de falha WhatsApp recebido",
  CONVERSATION_CREATED_FROM_WHATSAPP: "Conversa criada via WhatsApp",
  CONVERSATION_REOPENED_FROM_WHATSAPP: "Conversa reaberta via WhatsApp",
  PATIENT_MATCHED_FROM_WHATSAPP: "Paciente associado via WhatsApp",
  PATIENT_MATCH_AMBIGUOUS_FROM_WHATSAPP: "Associação de paciente ambígua via WhatsApp",
  PATIENT_CREATED_FROM_WHATSAPP: "Paciente criado via WhatsApp",
  CLINIC_CREATED: "Clínica criada",
  USER_CREATED: "Usuário criado",
}

export function getAuditActionLabel(action: string): string {
  return auditActionLabels[action] ?? action
}

/**
 * Visual severity buckets for badge coloring in the audit UI.
 * "danger" for security-relevant failures, "warning" for sensitive changes,
 * "info" for routine events.
 */
export function getAuditActionTone(action: string): "danger" | "warning" | "success" | "info" {
  if (
    action === "AUTH_LOGIN_FAILED" ||
    action === "ACCESS_DENIED" ||
    action === "USER_ACCESS_DENIED" ||
    action === "PATIENT_ACCESS_DENIED" ||
    action === "PROFESSIONAL_ACCESS_DENIED" ||
    action === "SERVICE_ACCESS_DENIED" ||
    action === "APPOINTMENT_ACCESS_DENIED" ||
    action === "APPOINTMENT_CANCELLED" ||
    action === "APPOINTMENT_NO_SHOW" ||
    action === "CONVERSATION_ACCESS_DENIED" ||
    action === "ASSIST_ACCESS_DENIED" ||
    action === "ASSIST_APPOINTMENT_CANCELLED" ||
    action === "ASSIST_AI_PROVIDER_FAILED" ||
    action === "ASSIST_TOOL_FAILED" ||
    action === "ASSIST_INVALID_AI_OUTPUT" ||
    action === "ASSIST_SENSITIVE_MESSAGE_DETECTED" ||
    action === "ASSIST_FLOW_FAILED" ||
    action === "ASSIST_HIGH_RISK_MESSAGE_DETECTED" ||
    action === "ASSIST_CRITICAL_RISK_MESSAGE_DETECTED" ||
    action === "ASSIST_PROMPT_INJECTION_DETECTED" ||
    action === "ASSIST_TOOL_BLOCKED" ||
    action === "ASSIST_DAILY_LIMIT_EXCEEDED" ||
    action === "WHATSAPP_ACCESS_DENIED" ||
    action === "WHATSAPP_WEBHOOK_SIGNATURE_INVALID" ||
    action === "WHATSAPP_WEBHOOK_VERIFICATION_FAILED" ||
    action === "WHATSAPP_STATUS_FAILED_RECEIVED"
  ) {
    return "danger"
  }
  if (
    action === "AUTH_PASSWORD_CHANGED" ||
    action === "USER_ROLE_CHANGED" ||
    action === "USER_STATUS_CHANGED" ||
    action === "USER_TEMP_PASSWORD_RESET" ||
    action === "PATIENT_STATUS_CHANGED" ||
    action === "PATIENT_ARCHIVED" ||
    action === "PROFESSIONAL_STATUS_CHANGED" ||
    action === "SERVICE_STATUS_CHANGED" ||
    action === "WORKING_HOUR_DELETED" ||
    action === "PROFESSIONAL_SERVICE_UNLINKED" ||
    action === "APPOINTMENT_RESCHEDULED" ||
    action === "CONVERSATION_CLOSED" ||
    action === "CONVERSATION_TRANSFERRED_TO_HUMAN" ||
    action === "CONVERSATION_RETURNED_TO_AI" ||
    action === "ASSIST_TRANSFERRED_TO_HUMAN" ||
    action === "ASSIST_APPOINTMENT_RESCHEDULED" ||
    action === "AI_SETTINGS_UPDATED" ||
    action === "AI_KNOWLEDGE_STATUS_CHANGED" ||
    action === "ASSIST_RULE_BASED_FALLBACK_USED" ||
    action === "ASSIST_FLOW_CANCELLED_BY_PATIENT" ||
    action === "ASSIST_RATE_LIMIT_EXCEEDED" ||
    action === "ASSIST_GLOBAL_DISABLED" ||
    action === "ASSIST_CLINIC_DISABLED" ||
    action === "ASSIST_LOOP_DETECTED" ||
    action === "WHATSAPP_CONFIG_INVALID" ||
    action === "WHATSAPP_WEBHOOK_DISABLED" ||
    action === "WHATSAPP_WEBHOOK_EVENT_IGNORED" ||
    action === "WHATSAPP_MESSAGE_DUPLICATE_IGNORED" ||
    action === "PATIENT_MATCH_AMBIGUOUS_FROM_WHATSAPP"
  ) {
    return "warning"
  }
  if (
    action === "AUTH_LOGIN_SUCCESS" ||
    action.endsWith("_CREATED") ||
    action === "PROFESSIONAL_SERVICE_LINKED" ||
    action === "APPOINTMENT_CONFIRMED" ||
    action === "APPOINTMENT_COMPLETED" ||
    action === "CONVERSATION_TAKEN" ||
    action === "CONVERSATION_REOPENED" ||
    action === "ASSIST_APPOINTMENT_CONFIRMED" ||
    action === "ASSIST_TOOL_EXECUTED" ||
    action === "ASSIST_SLOT_SELECTED" ||
    action === "ASSIST_FLOW_COMPLETED" ||
    action === "WHATSAPP_CONFIG_READY" ||
    action === "WHATSAPP_WEBHOOK_VERIFIED" ||
    action === "WHATSAPP_MESSAGE_RECEIVED" ||
    action === "CONVERSATION_CREATED_FROM_WHATSAPP" ||
    action === "PATIENT_MATCHED_FROM_WHATSAPP" ||
    action === "PATIENT_CREATED_FROM_WHATSAPP"
  ) {
    return "success"
  }
  return "info"
}
